# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-22 09:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='itemFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('descriptionShort', models.CharField(max_length=50)),
                ('descriptionLong', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('featured', models.BooleanField(default=True)),
                ('showItem', models.BooleanField(default=True)),
                ('image_1', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%D/')),
                ('image_2', models.FileField(blank=True, null=True, upload_to='')),
                ('chefId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='userInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chefName', models.CharField(blank=True, max_length=30, null=True)),
                ('about', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('message', models.CharField(max_length=50, null=True)),
                ('profile_pic1', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%D/')),
                ('profile_pic2', models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%D/')),
            ],
        ),
    ]
