# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-01 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfo',
            name='message',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
