# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 09:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20180603_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemfood',
            name='chefId',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
