# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-03 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20180603_0932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemfood',
            old_name='descriptionLong',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='itemfood',
            old_name='chefId',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='itemfood',
            name='descriptionShort',
        ),
        migrations.AlterField(
            model_name='itemfood',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%D/'),
        ),
    ]
