# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-04 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20180603_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='about',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
