# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-10 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20180604_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='channelUrl',
            field=models.URLField(blank=True, null=True),
        ),
    ]
