# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-16 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_userinfo_channelurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='profileDetail',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='itemfood',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
