# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-16 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20180616_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='showcase1',
            field=models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%D/'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='showcase2',
            field=models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%D/'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='showcase3',
            field=models.ImageField(blank=True, null=True, upload_to='media/%Y/%m/%D/'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='message',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
